services:
  backend:
    build: ./backend
    environment:
      PG_HOST: ${PG_HOST}
      PG_PORT: ${PG_PORT}
      PG_USER: ${PG_USER}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_DB: ${PG_DB}
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - ${VITE_API_PORT}:${VITE_API_PORT}
    depends_on:
      - db

  db:
    image: postgres:${PG_VERSION}
    restart: always
    environment:
      POSTGRES_DB: ${PG_DB}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    ports:
      - ${PG_PORT}:${PG_PORT}

  frontend:
    build: ./frontend
    ports:
      - ${VITE_PORT}:${VITE_PORT}
    volumes:
      - ./frontend:/app
      - /app/node_modules