services:
  backend:
    hostname: backend
    container_name: backend
    build: ./backend
    environment:
      PG_HOST: ${PG_HOST}
      PG_PORT: ${PG_PORT}
      PG_USER: ${PG_USER}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_DB: ${PG_DB}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      GOOGLE_MAPS_API_KEY: ${GOOGLE_MAPS_API_KEY}
      TZ: ${TZ}
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - ${API_PORT}:${API_PORT}
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - app-network

  db:
    hostname: db
    container_name: db
    image: postgres:${PG_VERSION}
    restart: always
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${PG_DB}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      TZ: ${TZ}
    ports:
      - ${PG_PORT}:${PG_PORT}
    env_file:
      - .env
    networks:
      - app-network

  redis:
    hostname: redis
    container_name: redis
    image: redis:alpine
    restart: always
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    env_file:
      - .env
    volumes:
      - redis-store:/data
    networks:
      - app-network

  frontend:
    container_name: frontend
    hostname: frontend
    build: ./frontend
    ports:
      - ${VITE_APP_PORT}:${VITE_APP_PORT}
    env_file:
      - .env
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - .env:/app/.env
    networks:
      - app-network

volumes:
  db-store:
  redis-store:

networks:
  app-network:
    driver: bridge
