# previews:
#   generation: automatic # Enable preview environments

# List all services *except* PostgreSQL databases here
services:
  # A web service that builds from a Dockerfile
  - type: web
    runtime: docker
    name: ekiview-backend
    plan: starter
    # repo: https://github.com/render-examples/webdis.git # Default: Repo containing render.yaml
    rootDir: ./backend
    # dockerCommand: ./webdis.sh # Default: Dockerfile CMD
    # scaling: # Autoscaling configuration
    #   minInstances: 1
    #   maxInstances: 3
    #   targetMemoryPercent: 60 # Optional if targetCPUPercent is set
    #   targetCPUPercent: 60    # Optional if targetMemory is set
    # healthCheckPath: /
    # registryCredential: # Default: No credential
    #   fromRegistryCreds:
    #     name: my-credentials
    region: singapore
    envVars:
      - key: PG_USER
        fromDatabase:
          name: ekiview-db
          property: user
      - key: PG_PASSWORD
        fromDatabase:
          name: ekiview-db
          property: password
      - key: PG_DB
        fromDatabase:
          name: ekiview-db
          property: database
      - key: PG_URL
        fromDatabase:
          name: ekiview-db
          property: connectionString
      - key: REDIS_HOST
        fromService:
          type: redis
          name: ekiview-redis
          property: host
      - key: REDIS_PORT
        fromService:
          type: redis
          name: ekiview-redis
          property: port
      - key: VITE_APP_URL
        value: https://ekiview.onrender.com
      - key: GOOGLE_MAPS_API_KEY
        sync: false

  - type: web
    runtime: docker
    name: ekiview
    plan: starter
    region: singapore
    rootDir: ./frontend

# A Redis instance
  - type: redis
    name: ekiview-redis
    ipAllowList: # Required
      - source: 0.0.0.0/0
        description: everywhere
    plan: free
    region: singapore
    maxmemoryPolicy: noeviction

# List all PostgreSQL databases here
databases:

  # A database with a read replica
  - name: ekiview-db
    plan: free
    region: singapore
    postgresMajorVersion: "13"
    databaseName: ekiview_production
    user: root
    # ipAllowList: # Optional (defaults to allow all)
    #   - source: 203.0.113.4/30
    #     description: office
    #   - source: 198.51.100.1
    #     description: home
    # readReplicas:
    #   - name: elephant-replica
